version: "3.8"
services:
    backend:
        container_name: "spmit_backend"
        build:
            context: ../backend
            dockerfile: Dockerfile_dev
        ports:
            - "5000:5000"
        volumes:
            - "../backend:/backend"
    mongo:
        container_name: "spmit_db"
        image: mongo
        restart: always
        ports:
            - "27017:27017"
